version: 2.0.{build}
branches:
  only:
  - master
image: Visual Studio 2019
configuration: Release
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  project: Cinegy.TtxDecoder.sln
  publish_nuget: true
  verbosity: minimal
before_build:
- cmd: nuget restore
after_build:
- cmd: >-
    7z a Cinegy.TtxDecoder-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip %APPVEYOR_BUILD_FOLDER%\Cinegy.TtxDecoder\bin

    appveyor PushArtifact Cinegy.TtxDecoder-%APPVEYOR_REPO_BRANCH%-%APPVEYOR_BUILD_VERSION%-PDB.zip
deploy:
- provider: NuGet
  api_key:
    secure: 1jfyZpEk52YsOKOQmOWEZYcglb8KoKUpN9l0qjhkasGbh3Fvts2VqxiLAvu+Uamy
  skip_symbols: true